name = "SpecificationExtraction"
uuid = "50dc28ac-0f47-49cd-a042-38ed5c54d180"
authors = ["Jaap de Jong <jaapdejong15@gmail.com>"]
version = "0.1.0"

[deps]
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
ProgressBars = "1.4.1"
julia = "1.6"